sudo: false
language: python
python:
  - '2.7'
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
script: 
  - pyb -X run_unit_tests
after_success:
  - coveralls --verbose
before_deploy:
  - pyb -v -X package
deploy:
  provider: pypi
  user: Immobilienscout24
  password:
    secure: yyyyy
  distributions: 'sdist'
  skip_cleanup: true
  on:
    repo: Immobilienscout24/aws-lambda-configurer
    branch: stable
    python: '3.5'
